name: Build

on: push

jobs:
    build:
        runs-on: ubuntu-latest # windows-latest | macos-latest
        name: Build
        steps:
            - name: Get repo
              uses: actions/checkout@v2

            - name: Get changed files
              uses: actions/setup-node@v2

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Format files
              run: npm run lint
