name: Update all docs

on:
    schedule:
        - cron: '0 0 * * *' # every day at midnight

jobs:
    run-benchmark:
        runs-on: ubuntu-latest # windows-latest | macos-latest
        name: Run all benchmarks
        steps:
            - name: Get repo
              uses: actions/checkout@v2
              with:
                  ref: docs

            - name: Delete current docs
              run: rm -rf docs && rm -rf SUMMARY.md && rm -rf SUMMARY-ALT.md

            - name: Setup node
              uses: actions/setup-node@v2

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Run benchmark for all modified files
              run: npm start

            - name: Format files
              run: npm run format

            - name: Push changes
              run: |
                  git add -A
                  git config --global user.name 'Github Action'
                  git config --global user.email 'github-action@noreply.github.com'
                  git commit -am "Updated Benchmarks"
                  git push
