name: Update docs on file change

on:
    pull_request:
        branches:
            - main

jobs:
    run-benchmark:
        runs-on: ubuntu-latest # windows-latest | macos-latest
        name: Run benchmarks for changed-files
        steps:
            - name: Get repo
              uses: actions/checkout@v2

            - name: Get changed files
              uses: actions/setup-node@v2

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Run benchmarks for all modified files
              run: npm run start:changes

            - name: Format files
              run: npm run format

            - name: Push changes
              run: |
                  git checkout -b docs
                  git config --global user.name 'Github Action'
                  git config --global user.email 'github-action@noreply.github.com'
                  git commit -am "Updated Benchmarks"
                  git push
