name: Update all docs on manual trigger

on: workflow_dispatch

jobs:
    run-benchmark:
        runs-on: ubuntu-latest # windows-latest | macos-latest
        name: Run benchmarks for changed-files
        steps:
            - name: Get repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.

            - name: Get changed files
              uses: actions/setup-node@v2

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Run benchmarks for all modified files
              run: npm start commit-changes
              
            - name: ls
              run: ls -ltr
              
            - name: push
              uses: dciborow/commit@0.0.2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  push-branch: main
                  commit-message: 'Benchmarks update'
