name: Sync main to docs

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    merge-branch:
        runs-on: ubuntu-latest # windows-latest | macos-latest
        steps:
            - name: Get repo
              uses: actions/checkout@v2

            - name: Merge main -> docs
              uses: devmasx/merge-branch@master
              with:
                  type: now
                  target_branch: docs
                  github_token: ${{ github.token }}
